# Generated by Django 3.0.5 on 2020-10-03 00:57

import api.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('shift', models.TextField()),
                ('timestamp', models.FloatField()),
                ('terminal', models.TextField()),
                ('lines', djongo.models.fields.ArrayField(model_container=api.models.Line)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
